Repository team3-hogwartsCommunity/BE-HogwartCommuity, pull requests merged in 2023-02, with the labels that each got.

#8 Feat: 로그인 구현, 회원가입 추가 #2 #3
  src/main/java/com/sparta/spartaminiproject/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartaminiproject/domain/user/dto/UserDto.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: enhancement, good first issue

#9 Feat: 게시판 기능 구현 #5
  src/main/java/com/sparta/spartaminiproject/common/entity/Timestamped.java
  src/main/java/com/sparta/spartaminiproject/domain/board/controller/BoardController.java
  src/main/java/com/sparta/spartaminiproject/domain/board/dto/BoardDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/dto/BoardRequestDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/entity/Board.java
  src/main/java/com/sparta/spartaminiproject/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
Labels: enhancement, good first issue

#10 Feat: jwt 구현 #4
  src/main/java/com/sparta/spartaminiproject/common/dto/SendMessageDto.java
  src/main/java/com/sparta/spartaminiproject/common/jwt/JwtUtil.java
  src/main/java/com/sparta/spartaminiproject/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: enhancement

#11 Feat: 댓글 기능 구현
  src/main/java/com/sparta/spartaminiproject/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/entity/Board.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/dto/CommentDto.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/entity/Comment.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/service/CommentService.java
Labels: enhancement, good first issue

#16 Feat: springsecurity 구현 #13
  src/main/java/com/sparta/spartaminiproject/common/security/config/WebConfig.java
  src/main/java/com/sparta/spartaminiproject/common/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/spartaminiproject/common/security/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/spartaminiproject/common/security/jwt/JwtUtil.java
  src/main/java/com/sparta/spartaminiproject/common/security/user/UserDetailsImpl.java
  src/main/java/com/sparta/spartaminiproject/common/security/user/UserDetailsServiceImpl.java
  src/main/java/com/sparta/spartaminiproject/domain/user/entity/UserDormitory.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: enhancement

#20 Feat: 게시글 좋아요 구현 #14
  src/main/java/com/sparta/spartaminiproject/common/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/spartaminiproject/common/security/jwt/JwtUtil.java
  src/main/java/com/sparta/spartaminiproject/domain/board/controller/BoardController.java
  src/main/java/com/sparta/spartaminiproject/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/entity/Board.java
  src/main/java/com/sparta/spartaminiproject/domain/board/entity/BoardLike.java
  src/main/java/com/sparta/spartaminiproject/domain/board/repository/BoardLikeRepository.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
Labels: enhancement

#21 Refactor: userservice 수정(코드 간소화) #18
  src/main/java/com/sparta/spartaminiproject/common/dto/SendMessageDto.java
  src/main/java/com/sparta/spartaminiproject/common/utill/SuccessCode.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: documentation

#22 Feat: 게시판 페이징 구현 #12
  src/main/java/com/sparta/spartaminiproject/domain/board/controller/BoardController.java
  src/main/java/com/sparta/spartaminiproject/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
Labels: enhancement

#23 Refactor: userservice 수정(암호화) #19
  src/main/java/com/sparta/spartaminiproject/common/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: documentation

#26 Refactor: userservice 수정(기숙사) #25
  src/main/java/com/sparta/spartaminiproject/domain/user/dto/UserDto.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: documentation

#29 Feat: 게시글 인가, 해당 게시글 작성자 확인 기능 구현 #17
  src/main/java/com/sparta/spartaminiproject/domain/board/controller/BoardController.java
  src/main/java/com/sparta/spartaminiproject/domain/board/entity/Board.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
Labels: enhancement
