Repository team3-hogwartsCommunity/BE-HogwartCommuity, pull requests merged in 2023-03, with the labels that each got.

#34 Feat: 댓글 수정, 삭제 권한 확인 구현 #28
  src/main/java/com/sparta/spartaminiproject/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/service/CommentService.java
Labels: enhancement, good first issue

#38 Feat: recomment 구현 #31
  src/main/java/com/sparta/spartaminiproject/domain/board/controller/BoardController.java
  src/main/java/com/sparta/spartaminiproject/domain/board/dto/BoardRequestDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/dto/CommentDto.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/entity/Comment.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/controller/ReCommentController.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/dto/ReCommentDto.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/entity/ReComment.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/entity/ReCommentLike.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/repository/ReCommentRepository.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/service/ReCommentService.java
Labels: enhancement

#40 Feat: 게시글 댓글에 username 데이터 추가 #35
  src/main/java/com/sparta/spartaminiproject/common/security/jwt/JwtUtil.java
  src/main/java/com/sparta/spartaminiproject/common/security/user/UserDetailsImpl.java
  src/main/java/com/sparta/spartaminiproject/common/utill/UserDormitory.java
  src/main/java/com/sparta/spartaminiproject/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/entity/Board.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/dto/CommentDto.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/dto/ReCommentDto.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/service/ReCommentService.java
  src/main/java/com/sparta/spartaminiproject/domain/user/dto/UserDto.java
  src/main/java/com/sparta/spartaminiproject/domain/user/entity/User.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: enhancement

#45 Feat: recomment like 구현 #31
  src/main/java/com/sparta/spartaminiproject/domain/recomment/controller/ReCommentController.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/repository/ReCommentLikeRepository.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/service/ReCommentService.java
Labels: enhancement

#47 Refactor: successCode 수정 #31
  src/main/java/com/sparta/spartaminiproject/common/utill/SuccessCode.java
Labels: documentation

#48 Feat: 게시글 총 페이지 응답 #46
  src/main/java/com/sparta/spartaminiproject/domain/board/controller/BoardController.java
  src/main/java/com/sparta/spartaminiproject/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
Labels: enhancement

#49 Refactor: 응답 SendMessageDto로 코드 변경 #24
  src/main/java/com/sparta/spartaminiproject/domain/board/controller/BoardController.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/service/CommentService.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/controller/ReCommentController.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/service/ReCommentService.java
  src/main/java/com/sparta/spartaminiproject/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: documentation

#52 Feat: GlobalExceptionHandler 구현 #36
  src/main/java/com/sparta/spartaminiproject/common/dto/SendMessageDto.java
  src/main/java/com/sparta/spartaminiproject/domain/board/controller/BoardController.java
  src/main/java/com/sparta/spartaminiproject/domain/board/service/BoardService.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/spartaminiproject/domain/comment/service/CommentService.java
  src/main/java/com/sparta/spartaminiproject/domain/recomment/controller/ReCommentController.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
  src/main/java/com/sparta/spartaminiproject/exception/CustomException.java
  src/main/java/com/sparta/spartaminiproject/exception/ErrorCode.java
  src/main/java/com/sparta/spartaminiproject/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/spartaminiproject/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/spartaminiproject/security/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/spartaminiproject/security/jwt/JwtUtil.java
  src/main/java/com/sparta/spartaminiproject/security/user/UserDetailsImpl.java
  src/main/java/com/sparta/spartaminiproject/security/user/UserDetailsServiceImpl.java
Labels: enhancement

#55 Feat: 아이디 중복 구현 #51
  src/main/java/com/sparta/spartaminiproject/common/utill/SuccessCode.java
  src/main/java/com/sparta/spartaminiproject/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartaminiproject/domain/user/dto/UserDto.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: enhancement

#56 Feat: SecurityExceptionHandler 구현 #53
  src/main/java/com/sparta/spartaminiproject/common/dto/SendMessageDto.java
  src/main/java/com/sparta/spartaminiproject/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/spartaminiproject/security/filter/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/spartaminiproject/security/filter/CustomAuthenticationEntryPoint.java
Labels: enhancement

#60 Feature/domain/user/dormitory
  src/main/java/com/sparta/spartaminiproject/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartaminiproject/domain/user/dto/UserDto.java
  src/main/java/com/sparta/spartaminiproject/domain/user/entity/User.java
  src/main/java/com/sparta/spartaminiproject/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
Labels: documentation, enhancement

#61 Feat: 로그아웃 구현#30
  src/main/java/com/sparta/spartaminiproject/common/utill/SuccessCode.java
  src/main/java/com/sparta/spartaminiproject/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartaminiproject/domain/user/service/UserService.java
  src/main/java/com/sparta/spartaminiproject/exception/ErrorCode.java
  src/main/java/com/sparta/spartaminiproject/security/jwt/JwtUtil.java
Labels: enhancement
